Traceback (most recent call last):
  File "map_matching/map_matcher.py", line 35, in <module>
    import map_matching as mm
  File "/Users/stipancicjosh/mapmatching-project/3. ViterbiHMM/Code/map_matching/map_matching.py", line 5, in <module>
    from geopy.distance import vincenty
  File "/Library/Python/2.7/site-packages/geopy/__init__.py", line 12, in <module>
    from geopy.geocoders import *  # noqa
  File "/Library/Python/2.7/site-packages/geopy/geocoders/__init__.py", line 120, in <module>
    from geopy.geocoders.arcgis import ArcGIS
  File "/Library/Python/2.7/site-packages/geopy/geocoders/arcgis.py", line 5, in <module>
    from geopy.compat import Request, string_compare, urlencode
  File "/Library/Python/2.7/site-packages/geopy/compat.py", line 79, in <module>
    from urllib2 import (HTTPBasicAuthHandler, HTTPError,  # noqa
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 94, in <module>
    import httplib
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 80, in <module>
    import mimetools
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 43, in <module>
    import fcntl as _fcntl
KeyboardInterrupt
